name: Test

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  Network-Connected-Test-macOS13:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Install
        run: bash sd-installer.sh -t -1 | grep -q 'Launching Web UI with arguments' && echo '成功 Success' && exit 0
        shell: /bin/bash --noprofile --norc -e {0}

  Network-Connected-Test-macOS12:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Install
        run: bash sd-installer.sh -t -1 | grep -q 'Launching Web UI with arguments' && echo '成功 Success' && exit 0
        shell: /bin/bash --noprofile --norc -e {0}

  Network-Not-Connected-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Install
        run: bash sd-installer.sh -t -2 | grep -q 'Launching Web UI with arguments' && echo '成功 Success' && exit 0
        shell: /bin/bash --noprofile --norc -e {0}
