name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Yes-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - run: pwd
      - run: ls
      - run: ls -la ${{ github.workspace }}
      - name: Yes
        run: yes | bash ${{ github.workspace }}/StableDiffusion-Installer-For-Mac/sd-installer.sh

  No-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: No
        run: yes n | bash ${{ github.workspace }}/StableDiffusion-Installer-For-Mac/sd-installer.sh
