name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Yes-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Yes
        run: bash sd-installer.sh -1 | grep -q 'Launching Web UI with arguments' && echo "成功 Success" && exit 0
        shell: /bin/bash --noprofile --norc -e {0}

  No-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: No
        run: bash sd-installer.sh -2 | grep -q 'Launching Web UI with arguments' && echo "成功 Success" && exit 0
        shell: /bin/bash --noprofile --norc -e {0}
