name: Test

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  Network-Connected-Test-13:
    runs-on: macOS-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Install
        run: bash sd-installer.sh -t -1 | grep -q 'Launching Web UI with arguments' && echo "成功 Success" && exit 0
        shell: /bin/bash --noprofile --norc -e {0}

  Network-Connected-Test-12:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Install
        run: bash sd-installer.sh -t -1 | grep -q 'Launching Web UI with arguments' && echo "成功 Success" && exit 0
        shell: /bin/bash --noprofile --norc -e {0}

  Network-Not-Connected-Test:
    runs-on: macos-latest
    steps:
      - name: Install
        run: curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/wy-luke/StableDiffusion-Installer-For-Mac/main/sd-installer.sh | /bin/bash -s -- -c -t -2 | grep -q 'Launching Web UI with arguments' && echo "成功 Success" && exit 0
        shell: /bin/bash --noprofile --norc -e {0}
