name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Yes-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Yes
        run: |
          tty=$(tty)
          bash sd-installer.sh -1 | tee $tty | grep -q 'loading stable diffusion model' && echo "成功 Success" && exit
        shell: bash

  No-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: No
        run: |
          tty=$(tty)
          bash sd-installer.sh -2 | tee $tty | grep -q 'loading stable diffusion model' && echo "成功 Success" && exit
        shell: bash
