name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Yes-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: Yes
        run: |
          until bash sd-installer.sh -1 | grep -m 1 "Launching Web UI with arguments"; do : ; done
        shell: bash

  No-Test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: sd-installer.sh
          sparse-checkout-cone-mode: false
      - name: No
        run: until bash sd-installer.sh -2 | grep -m 1 "Launching Web UI with arguments"; do : ; done
        shell: bash
